-- This module is the root of the BreuilMezardConjectureCanonicalLaneLean Lean proof package.
import BreuilMezardConjectureCanonicalLaneLean.Basic
import BreuilMezardConjectureCanonicalLaneLean.SourcePackage
import BreuilMezardConjectureCanonicalLaneLean.SourceDependencies
import BreuilMezardConjectureCanonicalLaneLean.Formalization
import BreuilMezardConjectureCanonicalLaneLean.ReviewerBridge
import BreuilMezardConjectureCanonicalLaneLean.TheoremStatement
import BreuilMezardConjectureCanonicalLaneLean.MathlibObjects
import BreuilMezardConjectureCanonicalLaneLean.AdmissibleClass
import BreuilMezardConjectureCanonicalLaneLean.Projection
import BreuilMezardConjectureCanonicalLaneLean.BridgeLemmas
import BreuilMezardConjectureCanonicalLaneLean.GateLemmas
import BreuilMezardConjectureCanonicalLaneLean.FinalTheorem
import BreuilMezardConjectureCanonicalLaneLean.MathlibStatement
